create type public.notification_kind as enum ('new_comment', 'new_message', 'match_suggested', 'claim_received', 'claim_accepted', 'claim_rejected', 'handover_requested', 'listing_returned');
create table public.comments (id uuid primary key default gen_random_uuid(), listing_id uuid not null references public.listings(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete cascade, body text not null check (char_length(btrim(body)) between 1 and 2000), created_at timestamptz not null default now());
create table public.conversations (id uuid primary key default gen_random_uuid(), listing_id uuid references public.listings(id) on delete set null, created_at timestamptz not null default now());
create table public.conversation_members (conversation_id uuid not null references public.conversations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, last_read_at timestamptz, primary key (conversation_id, user_id));
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, sender_id uuid not null references public.profiles(id) on delete cascade, body text not null check (char_length(btrim(body)) between 1 and 4000), created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, kind public.notification_kind not null, payload jsonb not null default '{}', read_at timestamptz, created_at timestamptz not null default now());
create table public.user_blocks (blocker_id uuid not null references public.profiles(id) on delete cascade, blocked_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), primary key (blocker_id, blocked_id), check (blocker_id <> blocked_id));
create index comments_listing_idx on public.comments (listing_id, created_at); create index messages_conversation_idx on public.messages (conversation_id, created_at); create index notifications_user_idx on public.notifications (user_id, read_at, created_at desc);

create or replace function public.start_conversation(p_listing_id uuid, p_other_user_id uuid) returns uuid language plpgsql security definer set search_path = '' as $$
declare result_id uuid;
begin
  if auth.uid() is null or auth.uid() = p_other_user_id then raise exception 'A different signed-in user is required'; end if;
  if exists (select 1 from public.user_blocks where (blocker_id = auth.uid() and blocked_id = p_other_user_id) or (blocker_id = p_other_user_id and blocked_id = auth.uid())) then raise exception 'Conversation is unavailable'; end if;
  if not exists (select 1 from public.listings l where l.id = p_listing_id and public.can_view_listing(l.poster_id, auth.uid())) then raise exception 'Listing is unavailable'; end if;
  select c.id into result_id from public.conversations c join public.conversation_members a on a.conversation_id=c.id and a.user_id=auth.uid() join public.conversation_members b on b.conversation_id=c.id and b.user_id=p_other_user_id where c.listing_id=p_listing_id limit 1;
  if result_id is null then insert into public.conversations(listing_id) values (p_listing_id) returning id into result_id; insert into public.conversation_members(conversation_id,user_id) values (result_id,auth.uid()),(result_id,p_other_user_id); end if;
  return result_id;
end; $$;
create or replace function public.mark_conversation_read(p_conversation_id uuid) returns void language sql security definer set search_path = '' as $$ update public.conversation_members set last_read_at=now() where conversation_id=p_conversation_id and user_id=auth.uid() $$;
create or replace function public.create_notification(p_user uuid, p_kind public.notification_kind, p_payload jsonb) returns void language sql security definer set search_path = '' as $$ insert into public.notifications(user_id,kind,payload) values(p_user,p_kind,p_payload) $$;
create or replace function public.notify_comment() returns trigger language plpgsql security definer set search_path = '' as $$ declare poster uuid; begin select poster_id into poster from public.listings where id=new.listing_id; if poster <> new.author_id then perform public.create_notification(poster,'new_comment',jsonb_build_object('listing_id',new.listing_id)); end if; return new; end; $$;
create or replace function public.notify_message() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.notifications(user_id,kind,payload) select user_id,'new_message',jsonb_build_object('conversation_id',new.conversation_id) from public.conversation_members where conversation_id=new.conversation_id and user_id<>new.sender_id; return new; end; $$;
create trigger comments_notify after insert on public.comments for each row execute function public.notify_comment(); create trigger messages_notify after insert on public.messages for each row execute function public.notify_message();

alter table public.comments enable row level security; alter table public.conversations enable row level security; alter table public.conversation_members enable row level security; alter table public.messages enable row level security; alter table public.notifications enable row level security; alter table public.user_blocks enable row level security;
create policy "comments readable" on public.comments for select to authenticated using (true); create policy "author adds comments" on public.comments for insert to authenticated with check(author_id=(select auth.uid())); create policy "author deletes comments" on public.comments for delete to authenticated using(author_id=(select auth.uid()));
create policy "members view conversations" on public.conversations for select to authenticated using(exists(select 1 from public.conversation_members m where m.conversation_id=id and m.user_id=(select auth.uid())));
create policy "members view memberships" on public.conversation_members for select to authenticated using(exists(select 1 from public.conversation_members m where m.conversation_id=conversation_id and m.user_id=(select auth.uid()))); create policy "members view messages" on public.messages for select to authenticated using(exists(select 1 from public.conversation_members m where m.conversation_id=conversation_id and m.user_id=(select auth.uid())) and not exists(select 1 from public.user_blocks b where b.blocker_id=(select auth.uid()) and b.blocked_id=sender_id)); create policy "members send messages" on public.messages for insert to authenticated with check(sender_id=(select auth.uid()) and exists(select 1 from public.conversation_members m where m.conversation_id=conversation_id and m.user_id=(select auth.uid())) and not exists(select 1 from public.user_blocks b join public.conversation_members m on m.conversation_id=conversation_id where b.blocker_id=m.user_id and b.blocked_id=(select auth.uid())));
create policy "own notifications" on public.notifications for select to authenticated using(user_id=(select auth.uid())); create policy "mark own notifications" on public.notifications for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid())); create policy "manage own blocks" on public.user_blocks for all to authenticated using(blocker_id=(select auth.uid())) with check(blocker_id=(select auth.uid()));
revoke all on public.comments,public.conversations,public.conversation_members,public.messages,public.notifications,public.user_blocks from anon,authenticated; grant select,insert,delete on public.comments to authenticated; grant select on public.conversations,public.conversation_members,public.messages,public.notifications to authenticated; grant insert on public.messages to authenticated; grant update(read_at) on public.notifications to authenticated; grant select,insert,delete on public.user_blocks to authenticated; revoke execute on function public.start_conversation(uuid,uuid),public.mark_conversation_read(uuid),public.create_notification(uuid,public.notification_kind,jsonb),public.notify_comment(),public.notify_message() from public,anon; grant execute on function public.start_conversation(uuid,uuid),public.mark_conversation_read(uuid) to authenticated;
